name: moehnen
favicon: null
layout_spectrum: 0.31528
typography_spectrum: 0.55941
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#132780'
    - '#ff2400'
    - '#ffffff'
    - '#4e5d9f'
    - '#97a0c7'
  brandStrength: 0.8328089320566505
  lightness: 0.8918246091343462
  saturation: 0.3710787408053875
  rhythmicContrast: 0.9659281298518181
purpose: []
