name: moehnen
favicon: null
layout_spectrum: 0.7728376160375774
typography_spectrum: 0.8736787638626993
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.8328089320566505
  lightness: 0.8918246091343462
  saturation: 0.3710787408053875
  rhythmicContrast: 0.9659281298518181
purpose: []
